### ISSUE TITLE
Alarm App crashes 

### ISSUE THREAD

**Issue by karlemann** [miui-scandinavia/MA-XML-7.0-NORWEGIAN#3]
While using Norwegian language on 6.6.30, alarm apps immediately crashes upon opening. Using MI Note Pro.

**Comment by karlemann** [comment]
should be app*, not apps.

**Comment by ingbrzy** [comment]
post log from crash here

**Comment by datagutt** [comment]
Hey,
I will try to fix this once my translation is up-to-date for MIUI 8.
It will be get fixed by Fridays release.

**Comment by karlemann** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.deskclock/com.android.deskclock.DeskClockTabActivity}: java.lang.ArrayIndexOutOfBoundsException: length=295; index=295
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java)
    at android.app.ActivityThread.access$900(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
    at android.os.Handler.dispatchMessage(Handler.java)
    at android.os.Looper.loop(Looper.java)
    at android.app.ActivityThread.main(ActivityThread.java)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=295; index=295
    at com.android.deskclock.util.CityZoneHelper.loadCitiesFromXml(CityZoneHelper.java)
    at com.android.deskclock.util.CityZoneHelper.<init>(CityZoneHelper.java)
    at com.android.deskclock.fragments.WorldClockFragment$TimezoneAdapter.<init>(WorldClockFragment.java)
    at com.android.deskclock.fragments.WorldClockFragment.onCreateView(WorldClockFragment.java)
    at android.app.Fragment.performCreateView(Fragment.java)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
    at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java)
    at android.app.Activity.performCreateCommon(Activity.java)
    at android.app.Activity.performCreate(Activity.java)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
    ... 12 more

**Comment by karlemann** [comment]
java.lang.ArrayIndexOutOfBoundsException: length=295; index=295
    at com.android.deskclock.util.CityZoneHelper.loadCitiesFromXml(CityZoneHelper.java)
    at com.android.deskclock.util.CityZoneHelper.<init>(CityZoneHelper.java)
    at com.android.deskclock.fragments.WorldClockFragment$TimezoneAdapter.<init>(WorldClockFragment.java)
    at com.android.deskclock.fragments.WorldClockFragment.onCreateView(WorldClockFragment.java)
    at android.app.Fragment.performCreateView(Fragment.java)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
    at android.app.BackStackRecord.run(BackStackRecord.java)
    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java)
    at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java)
    at com.android.deskclock.controller.DynamicFragmentPagerAdapter.finishUpdate(DynamicFragmentPagerAdapter.java)
    at miui.view.ViewPager.V(SourceFile)
    at miui.view.ViewPager.dw(SourceFile)
    at miui.view.ViewPager.onMeasure(SourceFile)
    at android.view.View.measure(View.java)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java)
    at android.view.View.measure(View.java)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java)
    at android.view.View.measure(View.java)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java)
    at android.view.View.measure(View.java)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
    at com.miui.internal.widget.ActionBarOverlayLayout.onMeasure(SourceFile)
    at android.view.View.measure(View.java)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2618)
    at android.view.View.measure(View.java)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java)
    at android.view.Choreographer.doCallbacks(Choreographer.java)
    at android.view.Choreographer.doFrame(Choreographer.java)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)
    at android.os.Handler.handleCallback(Handler.java)
    at android.os.Handler.dispatchMessage(Handler.java)
    at android.os.Looper.loop(Looper.java)
    at android.app.ActivityThread.main(ActivityThread.java)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
